tags:
  - Roles
summary: Hapus peran
description: Menghapus peran berdasarkan ID
parameters:
  - name: id
    in: path
    required: true
    description: ID peran
    schema:
      type: integer
responses:
  "200":
    description: Peran berhasil dihapus
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: string
              nullable: true
              example: null
            message:
              type: string
              example: "Role deleted successfully"
            success:
              type: boolean
  "400":
    description: Permintaan tidak valid
    content:
      application/json:
        schema:
          type: object
          properties:
            error:
              type: string
            success:
              type: boolean
              example: false