openapi: 3.0.0
info:
  title: OpenAPI
  description: Dokumentasi OpenAPI
  version: 1.0.0
servers:
  - url: "http://127.0.0.1:5000/api/v1"
paths:
  /hello:
    get:
      tags:
        - Hello World
      summary: Hello World
      description: Mengembalikan pesan Hello World
      responses:
        "200":
          description: Berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, world!"
  /users:
    get:
      tags:
        - Users
      summary: Ambil semua pengguna
      description: Mengembalikan data semua pengguna
      responses:
        "200":
          description: Berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string
    post:
      tags:
        - Users
      summary: Tambah pengguna
      description: Menambahkan pengguna baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
      responses:
        "201":
          description: Pengguna berhasil ditambahkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Pengguna berhasil ditambahkan
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
  /positions:
    get:
      tags:
        - Positions
      summary: Ambil semua posisi
      description: Mengembalikan data semua posisi beserta informasi departemen
      responses:
        "200":
          description: Berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Backend Developer
                        department_id:
                          type: integer
                          example: 2
                        created_at:
                          type: string
                          format: date-time
                          example: "2025-07-04T13:51:51.901876+07:00"
                        updated_at:
                          type: string
                          format: date-time
                          example: "2025-07-04T13:53:29.343153+07:00"
                        has_department:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 2
                            name:
                              type: string
                              example: HR
                            created_at:
                              type: string
                              format: date-time
                              example: "2025-07-04T13:52:49.041189+07:00"
                            updated_at:
                              type: string
                              format: date-time
                              example: "2025-07-04T13:52:49.041769+07:00"
                  success:
                    type: boolean
                    example: true
    post:
      tags:
        - Positions
      summary: Buat posisi baru
      description: Membuat posisi baru dan mengembalikan data posisi yang telah dibuat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - department_id
              properties:
                name:
                  type: string
                  example: Frontend Developer
                  description: Nama posisi
                department_id:
                  type: integer
                  example: 1
                  description: ID departemen
      responses:
        "201":
          description: Posisi berhasil dibuat
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 3
                      name:
                        type: string
                        example: Frontend Developer
                      department_id:
                        type: integer
                        example: 1
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-07-04T14:04:06.937432+07:00"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-07-04T14:04:06.937432+07:00"
                  success:
                    type: boolean
                    example: true
        "400":
          description: Data tidak valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Data tidak valid
  "/positions/{id}":
    put:
      tags:
        - Positions
      summary: Update posisi
      description: Mengupdate posisi yang sudah ada dan mengembalikan data posisi yang telah diupdate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID posisi yang akan diupdate
          example: 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Frontend Developesr
                  description: Nama posisi baru
                department_id:
                  type: integer
                  example: 1
                  description: ID departemen baru
      responses:
        "200":
          description: Posisi berhasil diupdate
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 3
                      name:
                        type: string
                        example: Frontend Developesr
                      department_id:
                        type: integer
                        example: 1
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-07-04T14:04:06.937432+07:00"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-07-04T14:05:04.99301+07:00"
                  success:
                    type: boolean
                    example: true
        "400":
          description: Data tidak valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Data tidak valid
        "404":
          description: Posisi tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Posisi tidak ditemukan
    delete:
      tags:
        - Positions
      summary: Hapus posisi
      description: Menghapus posisi berdasarkan ID yang diberikan
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID posisi yang akan dihapus
          example: 3
      responses:
        "200":
          description: Posisi berhasil dihapus
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: "null"
                    example: null
                  message:
                    type: string
                    example: Position deleted successfully
                  success:
                    type: boolean
                    example: true
        "400":
          description: ID tidak valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: "null"
                    example: null
                  message:
                    type: string
                    example: Invalid ID
                  success:
                    type: boolean
                    example: false
        "404":
          description: Posisi tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: "null"
                    example: null
                  message:
                    type: string
                    example: Position not found
                  success:
                    type: boolean
                    example: false
