openapi: 3.0.0
info:
  title: OpenAPI
  description: Dokumentasi OpenAPI
  version: 1.0.0
servers:
  - url: 'http://localhost:5123/api'
paths:
  /hello:
    get:
      tags:
        - Hello World
      summary: Hello World
      description: Mengembalikan pesan Hello World
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, world!'
  /levels:
    get:
      tags:
        - Levels
      summary: Ambil semua level
      description: Mengembalikan data semua level
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
    post:
      tags:
        - Levels
      summary: Tambah level
      description: Menambahkan level baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Level 1
      responses:
        '201':
          description: Level berhasil ditambahkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Level berhasil ditambahkan
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
  '/levels/{id}':
    put:
      tags:
        - Levels
      summary: Ubah level
      description: Mengubah data level yang sudah ada berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID level yang ingin diubah
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Level 1
      responses:
        '200':
          description: Level berhasil diubah
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Level berhasil diubah
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '404':
          description: Level tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Level tidak ditemukan
    delete:
      tags:
        - Levels
      summary: Hapus level
      description: Menghapus data level berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID level yang ingin dihapus
      responses:
        '200':
          description: Level berhasil dihapus
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Level berhasil dihapus
        '404':
          description: Level tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Level tidak ditemukan
