openapi: 3.0.0
info:
  title: OpenAPI
  description: Dokumentasi OpenAPI
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/api/v1
paths:
  /hello:
    $ref: ./paths/hello/hello.get.yaml
  /levels:
    get:
      $ref: ./paths/levels/levels.get.yaml
    post:
      $ref: ./paths/levels/levels.post.yaml
  /levels/{id}:
    put:
      $ref: ./paths/levels/levels.put.yaml
    delete:
      $ref: ./paths/levels/levels.delete.yaml
  /titles:
    get:
      $ref: ./paths/titles/titles.get.yaml
    post:
      $ref: ./paths/titles/titles.post.yaml
  /titles/{id}:
    put:
      $ref: ./paths/titles/titles.put.yaml
    delete:
      $ref: ./paths/titles/titles.delete.yaml
  /positions:
    get:
      $ref: ./paths/positions/positions.get.yaml
    post:
      $ref: ./paths/positions/positions.post.yaml
  /positions/{id}:
    put:
      $ref: ./paths/positions/positions.put.yaml
    delete:
      $ref: ./paths/positions/positions.delete.yaml
  /users:
    get:
      $ref: ./paths/users/users.get.yaml
    post:
      $ref: ./paths/users/users.post.yaml
  /users/{id}:
    put:
      $ref: ./paths/users/users.put.yaml
    delete:
      $ref: ./paths/users/users.delete.yaml
