openapi: 3.0.0
info:
  title: OpenAPI
  description: Dokumentasi OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1
  - url: http://localhost:5123/api
paths:
  /hello:
    $ref: ./paths/hello/hello.get.yaml
  /levels:
    get:
      $ref: ./paths/levels/levels.get.yaml
    post:
      $ref: ./paths/levels/levels.post.yaml
  /levels/{id}:
    put:
      $ref: ./paths/levels/levels.put.yaml
    delete:
      $ref: ./paths/levels/levels.delete.yaml
