openapi: 3.0.0
info:
  title: OpenAPI
  description: Dokumentasi OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1
  - url: http://localhost:5123/api
paths:
  /hello:
    $ref: ./paths/hello/hello.get.yaml
  /users:
    get:
      $ref: ./paths/users/users.get.yaml
    post:
      $ref: ./paths/users/users.post.yaml
  /users/{id}:
    put:
      $ref: ./paths/users/users.put.yaml
    delete:
      $ref: ./paths/users/users.delete.yaml
