openapi: 3.0.0
info:
  title: OpenAPI
  description: Dokumentasi OpenAPI
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/api/v1
paths:
  /hello:
    $ref: ./paths/hello/hello.get.yaml
  /levels:
    get:
      $ref: ./paths/levels/levels.get.yaml
    post:
      $ref: ./paths/levels/levels.post.yaml
  /levels/{id}:
    put:
      $ref: ./paths/levels/levels.put.yaml
    delete:
      $ref: ./paths/levels/levels.delete.yaml
  /titles:
    get:
      $ref: ./paths/titles/titles.get.yaml
    post:
      $ref: ./paths/titles/titles.post.yaml
  /titles/{id}:
    put:
      $ref: ./paths/titles/titles.put.yaml
    delete:
      $ref: ./paths/titles/titles.delete.yaml
  /positions:
    get:
      $ref: ./paths/positions/positions.get.yaml
    post:
      $ref: ./paths/positions/positions.post.yaml
  /positions/{id}:
    put:
      $ref: ./paths/positions/positions.put.yaml
    delete:
      $ref: ./paths/positions/positions.delete.yaml
  /departments:
    get:
      $ref: ./paths/departments/departments.get.yaml
    post:
      $ref: ./paths/departments/departments.post.yaml
  /departments/{id}:
    put:
      $ref: ./paths/departments/departments.put.yaml
    delete:
      $ref: ./paths/departments/departments.delete.yaml
  /projects:
    get:
      $ref: ./paths/projects/projects.get.yaml
    post:
      $ref: ./paths/projects/projects.post.yaml
  /projects/{id}:
    put:
      $ref: ./paths/projects/projects.put.yaml
    delete:
      $ref: ./paths/projects/projects.delete.yaml
